name: Build
on:
  pull_request: {}
  push:
    branches:
      - master
    tags:
      - v*
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: Test (${{ matrix.scenario }})
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default-with-lockfile
          - ember-default-with-jquery
          - ember-release
          - ember-beta
          - ember-canary
          - ember-lts-3.16
          - ember-lts-3.20
          - embroider-safe
          # - embroider-optimized

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Volta
        uses: volta-cli/action@v1
      - name: Install dependencies
        run: npm ci
      - name: Setup ember-try scenario
        if: matrix.scenario != 'default-with-lockfile'
        run: >-
          npx ember try:one ${{ matrix.scenario }} --skip-cleanup ---
          '[ -z "$EMBER_OPTIONAL_FEATURES" ] || echo "EMBER_OPTIONAL_FEATURES=$EMBER_OPTIONAL_FEATURES" >> $GITHUB_ENV'
      - name: Lint
        run: npm run lint
      - name: Build
        run: npx ember build --environment test
      - name: Run test
        # Due to a bug in ember-cli, running `ember test` with `--path` doesn't set `EMBER_ENV=test`
        # See https://github.com/ember-cli/ember-cli/issues/8922
        run: EMBER_ENV=test npm run test:ember -- --path dist
